# Generated by Django 4.0.2 on 2022-02-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pichanga',
            new_name='Organization',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='pichanga',
            new_name='org',
        ),
        migrations.RenameField(
            model_name='picture',
            old_name='club',
            new_name='org',
        ),
        migrations.AlterField(
            model_name='member',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
