# Generated by Django 3.0.2 on 2020-01-15 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200115_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pichanga',
            name='logo',
        ),
    ]
