# Generated by Django 3.0.2 on 2020-01-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pichanga_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pichanga',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
